Fix correct closing of function

diff --git a/openstack/masakari/templates/configmap-cleanupDB.yaml b/openstack/masakari/templates/configmap-cleanupDB.yaml
--- a/openstack/masakari/templates/configmap-cleanupDB.yaml
+++ b/openstack/masakari/templates/configmap-cleanupDB.yaml
@@ -44,6 +44,10 @@ data:
           echo "Failed to delete rows."
           exit 1
         fi
+      else
+        echo "Failed to delete rows. One or more variables are empty."
+        exit 1
+      fi
     }
 
     # Deletes entries older than $DAYS from notifications table
