basic galera setup done - automatic bootstrap - rolling config upgrade - health checks for several MariaDB and Galera metrics - headless service option tweaked - more links added to documentation

diff --git a/common/mariadb-galera/helm/templates/configmap-checks.sh.yaml b/common/mariadb-galera/helm/templates/configmap-checks.sh.yaml
--- a/common/mariadb-galera/helm/templates/configmap-checks.sh.yaml
+++ b/common/mariadb-galera/helm/templates/configmap-checks.sh.yaml
@@ -12,7 +12,7 @@ data:
     set -o pipefail
     set +x
 
-    timeout {{ $.Values.livenessProbe.timeoutSeconds }} bash -c "</dev/tcp/${CONTAINER_IP}/${MYSQL_PORT}"
+    mysql --defaults-file=/opt/mariadb/etc/my.cnf --protocol=tcp -u root -h localhost --port=${MYSQL_PORT} --batch --connect-timeout={{ $.Values.livenessProbe.timeoutSeconds }} --execute="SHOW DATABASES;" | grep --silent 'mysql'
     if [ $? -eq 0 ]; then
       echo 'MariaDB MySQL API reachable'
     else
@@ -28,6 +28,22 @@ data:
       exit 1
     fi
 
+    mysql --defaults-file=/opt/${SOFTWARE_NAME}/etc/my.cnf --protocol=tcp -u root -h localhost --port=${MYSQL_PORT} --database=mysql --connect-timeout={{ $.Values.livenessProbe.timeoutSeconds }} --execute="SHOW GLOBAL STATUS LIKE 'wsrep_cluster_status';" | grep 'wsrep_cluster_status' | grep --silent 'Primary'
+    if [ $? -eq 0 ]; then
+      echo 'MariaDB Galera node reports a working cluster status'
+    else
+      echo 'MariaDB Galera node reports a not working cluster status'
+      exit 1
+    fi
+
+    mysql --defaults-file=/opt/${SOFTWARE_NAME}/etc/my.cnf --protocol=tcp -u root -h localhost --port=${MYSQL_PORT} --database=mysql --connect-timeout={{ $.Values.livenessProbe.timeoutSeconds }} --execute="SHOW GLOBAL STATUS LIKE 'wsrep_connected';" | grep 'wsrep_connected' | grep --silent 'ON'
+    if [ $? -eq 0 ]; then
+      echo 'MariaDB Galera node connected to other cluster nodes'
+    else
+      echo 'MariaDB Galera node not connected to other cluster nodes'
+      exit 1
+    fi
+
   readiness.sh: |-
     #!/usr/bin/env bash
     set +e
@@ -35,10 +51,26 @@ data:
     set -o pipefail
     set +x
 
-    mysql --defaults-file=/opt/${SOFTWARE_NAME}/etc/my.cnf -u root -h localhost --database=mysql --execute='STATUS;' | grep 'Server version:' | grep --silent "${SOFTWARE_VERSION}"
+    mysql --defaults-file=/opt/${SOFTWARE_NAME}/etc/my.cnf --protocol=tcp -u root -h localhost --port=${MYSQL_PORT} --database=mysql --connect-timeout={{ $.Values.readinessProbe.timeoutSeconds }} --execute="STATUS;" | grep 'Server version:' | grep --silent "${SOFTWARE_VERSION}"
     if [ $? -eq 0 ]; then
       echo 'MariaDB MySQL API usable'
     else
       echo 'MariaDB MySQL API not usable'
+      exit 1
+    fi
+
+    mysql --defaults-file=/opt/${SOFTWARE_NAME}/etc/my.cnf --protocol=tcp -u root -h localhost --port=${MYSQL_PORT} --database=mysql --connect-timeout={{ $.Values.readinessProbe.timeoutSeconds }} --execute="SHOW GLOBAL STATUS LIKE 'wsrep_local_state_comment';" | grep 'wsrep_local_state_comment' | grep --invert-match --silent 'Initialized'
+    if [ $? -eq 0 ]; then
+      echo 'MariaDB Galera node has not failed to join the cluster'
+    else
+      echo 'MariaDB Galera node has failed to join the cluster'
+      exit 1
+    fi
+
+    mysql --defaults-file=/opt/${SOFTWARE_NAME}/etc/my.cnf --protocol=tcp -u root -h localhost --port=${MYSQL_PORT} --database=mysql --connect-timeout={{ $.Values.readinessProbe.timeoutSeconds }} --execute="SHOW GLOBAL STATUS LIKE 'wsrep_ready';" | grep 'wsrep_ready' | grep --silent 'ON'
+    if [ $? -eq 0 ]; then
+      echo 'MariaDB Galera ready for queries'
+    else
+      echo 'MariaDB Galera not ready for queries'
       exit 1
     fi
diff --git a/common/mariadb-galera/helm/templates/configmap-entrypoint.sh.yaml b/common/mariadb-galera/helm/templates/configmap-entrypoint.sh.yaml
--- a/common/mariadb-galera/helm/templates/configmap-entrypoint.sh.yaml
+++ b/common/mariadb-galera/helm/templates/configmap-entrypoint.sh.yaml
@@ -14,6 +14,11 @@ data:
     set -o pipefail
     set +x
 
+    BASE=/opt/${SOFTWARE_NAME}
+    DATADIR=${BASE}/data
+    MAX_RETRIES=10
+    WAIT_SECONDS=6
+
     function logjson {
       printf "{\"@timestamp\":\"%s\",\"ecs.version\":\"1.6.0\",\"log.level\":\"%s\",\"message\":\"%s\"}\n" "$(date +%Y.%m.%d-%H:%M:%S-%Z)" "$2" "$3" >>/dev/"$1"
     }
@@ -26,13 +31,64 @@ data:
       logjson  "stderr" "error" "$1"
     }
 
-    function startdb {
-      loginfo "starting mariadbd process"
+    function templateconfig {
+      local int
+      for (( int=${MAX_RETRIES}; int >=1; int-=1));
+        do
+        loginfo "template MariaDB configurations (${int} retries left)"
+        cat ${BASE}/etc/conf.d/my.cnf.tpl | envsubst > ${BASE}/etc/conf.d/my.cnf
+        if [ $? -ne 0 ]; then
+          logerror "${BASE}/etc/conf.d/my.cnf.tpl rendering has been failed"
+          sleep ${WAIT_SECONDS}
+        else
+          break
+        fi
+      done
+      if [ ${int} = 0 ]; then
+        logerror "template MariaDB configurations has been finally failed"
+        exit 1
+      fi
+      loginfo "template MariaDB configurations done"
+    }
+
+    function initgalera {
+      if [ ${HOSTNAME} == "{{ $.Release.Name }}-0" ]; then
+        if [ -f ${DATADIR}/grastate.dat && -s ${DATADIR}/grastate.dat ]; then
+          loginfo "init Galera cluster configuration already done"
+          startgaleradb
+        else
+          local int
+          for (( int=${MAX_RETRIES}; int >=1; int-=1));
+            do
+            loginfo "init Galera cluster (${int} retries left)"
+            exec mariadbd --defaults-file=${BASE}/etc/my.cnf --basedir=/usr --wsrep-new-cluster
+            if [ $? -ne 0 ]; then
+              logerror "init Galera cluster has been failed"
+              sleep ${WAIT_SECONDS}
+            else
+              break
+            fi
+          done
+          if [ ${int} = 0 ]; then
+            logerror "init Galera cluster has been finally failed"
+            exit 1
+          fi
+          loginfo "init Galera cluster configurations done"
+        fi
+      else
+        loginfo "Galera cluster init will only be done on the first node"
+        startgaleradb
+      fi
+    }
+
+    function startgaleradb {
+      loginfo "starting mariadbd galera process"
       exec mariadbd --defaults-file=${BASE}/etc/my.cnf --basedir=/usr --skip-log-error
       if [ $? -ne 0 ]; then
-        logerror "mariadbd startup failed"
+        logerror "mariadbd galera startup failed"
         exit 1
       fi
     }
 
-    startdb
+    templateconfig
+    initgalera
