openstack/content-repo: improve logging when apk add fails

diff --git a/openstack/content-repo/bin/check-rhn b/openstack/content-repo/bin/check-rhn
--- a/openstack/content-repo/bin/check-rhn
+++ b/openstack/content-repo/bin/check-rhn
@@ -11,7 +11,7 @@ if [ -z "${CHECK_URL}" ]; then
     exit 1
 fi
 
-apk add --update curl || exit 1
+apk add --update curl || echo "apk add failed" ; exit 1
 
 ENTITLEMENT_PREFIX=rhel
 # Check for release specific entitlements
